from __future__ import annotations

"""Add repo + batch_id to initiative_phases, update primary key.

The URL hierarchy is now:
    Account → Project (repo) → Initiative → Batch → Phase → Issue

``initiative_phases`` previously used ``(initiative, phase_label)`` as its
primary key, meaning two repos with the same initiative name shared rows and
re-filing the same initiative overwrote phase metadata.  This migration
introduces proper scoping:

Changes
-------
- Add ``repo VARCHAR(256) NOT NULL DEFAULT ''`` — the GitHub ``{org}/{repo}``
  string (e.g. ``cgcardona/agentception``).  Existing rows receive an empty
  string sentinel; callers should backfill via ``reseed_missing_initiative_phases``.
- Add ``batch_id VARCHAR(128) NOT NULL DEFAULT 'legacy'`` — the filing batch
  identifier generated by ``file_issues``.  Existing rows are grouped under
  the sentinel ``'legacy'`` batch.
- Drop old primary key ``(initiative, phase_label)``.
- Create new primary key ``(repo, initiative, batch_id, phase_label)``.
- Drop old index ``ix_initiative_phases_initiative``.
- Create new index ``ix_initiative_phases_repo_initiative`` on ``(repo, initiative)``.

Revision ID: 0004
Revises: 0003
Create Date: 2026-03-07
"""

import sqlalchemy as sa
from alembic import op

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Add new columns with sentinel defaults for existing rows.
    op.add_column(
        "initiative_phases",
        sa.Column("repo", sa.String(256), nullable=False, server_default=""),
    )
    op.add_column(
        "initiative_phases",
        sa.Column("batch_id", sa.String(128), nullable=False, server_default="legacy"),
    )

    # 2. Drop the old primary key constraint.
    op.drop_constraint("initiative_phases_pkey", "initiative_phases", type_="primary")

    # 3. Establish the new composite primary key.
    op.create_primary_key(
        "initiative_phases_pkey",
        "initiative_phases",
        ["repo", "initiative", "batch_id", "phase_label"],
    )

    # 4. Replace the old single-column index with the new two-column one.
    op.drop_index("ix_initiative_phases_initiative", table_name="initiative_phases")
    op.create_index(
        "ix_initiative_phases_repo_initiative",
        "initiative_phases",
        ["repo", "initiative"],
    )


def downgrade() -> None:
    # Reverse the index changes.
    op.drop_index(
        "ix_initiative_phases_repo_initiative", table_name="initiative_phases"
    )
    op.create_index(
        "ix_initiative_phases_initiative", "initiative_phases", ["initiative"]
    )

    # Restore the old primary key (data may be ambiguous if multiple batches/repos
    # share the same initiative + phase_label — downgrade is best-effort).
    op.drop_constraint("initiative_phases_pkey", "initiative_phases", type_="primary")
    op.create_primary_key(
        "initiative_phases_pkey",
        "initiative_phases",
        ["initiative", "phase_label"],
    )

    # Remove the added columns.
    op.drop_column("initiative_phases", "batch_id")
    op.drop_column("initiative_phases", "repo")
